default:
  image: node:latest

cache:
  paths:
    - node_modules/

variables:
  SYSTEM_NAME: "cyberpunk-red-core"

stages:
  - init
  - test
  - build
  - pre-release
  - release

init:
  stage: init
  script:
    - echo "Installing dependencies..."
    - npm install

lint:
  stage: test
  script:
    - echo "Linting code..."
    - npm run lint
  needs:
    - job: init

unit-test:
  stage: test
  script:
    - echo "Executing tests..."
    - npm test
  needs:
    - job: init

test-shell-scripts:
  stage: test
  before_script:
    - apt-get update
    - apt-get install shellcheck
  script:
    - ./.gitlab/pipeline_tests/test-shell-scripts.sh
  only:
    changes:
      - "**/*.sh"
  needs:
    - job: init

language-unused-strings:
  stage: test
  script:
    - echo "Checking language file for unused strings..."
    - ./.gitlab/pipeline_tests/test-lang-file.sh
  needs:
    - job: init

language-exists:
  stage: test
  before_script:
    - apt-get update
    - apt-get install jq --yes
  script:
    - echo "Checking if all the language files specified in system.json exist..."
    - ./.gitlab/pipeline_tests/test-lang-existence.sh
  needs:
    - job: init

changelog-has-changed:
  stage: test
  script:
    - echo "Checking if the CHANGELOG.md changed..."
    - git fetch origin dev
    - ./.gitlab/pipeline_tests/test-changelog-dev-changed.sh
  allow_failure: true
  except:
    - master
    - dev
  needs:
    - job: init

trace-statements:
  stage: test
  script:
    - echo "Checking if there are proper trace statements in all hbs files..."
    - ./.gitlab/pipeline_tests/test-hbs-trace.sh
  needs:
    - job: init

code-localization:
  stage: test
  script:
    - echo "Checking if our own localization and notification code is used..."
    - ./.gitlab/pipeline_tests/test-misc.sh
  needs:
    - job: init

handlebars-helpers:
  stage: test
  script:
  - echo "Checking use of handlebars helpers..."
  - ./.gitlab/pipeline_tests/test-handlebars-helpers.sh
  needs:
    - job: init

# Build without artifacts when not tagging a release
test-build:
  stage: test
  except:
    - tags
  script:
    - echo "Building cyberpunk-red-core..."
    - npm run build
  needs:
    - job: init

# Builds and Uploads artifacts the gitlab generic repo
build-artifacts:
  stage: build
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install curl zip jq -y
  script:
    - echo "Building cyberpunk-red-core..."
    - ./.gitlab/pipeline_utils/build.sh
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
  needs:
    - job: unit-test
    - job: test-shell-scripts
      optional: true
    - job: language-unused-strings
    - job: language-exists
    - job: changelog-has-changed
    - job: trace-statements
    - job: code-localization
    - job: handlebars-helpers
    - job: test-build
      optional: true

# Creates a GitLab release with the previously uploaded artifacts
create-release:
  stage: build
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install curl jq -y
    - curl --silent --location --output /usr/local/bin/release-cli "https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
  script:
    - echo "Running Release Job..."
    - ./.gitlab/pipeline_utils/release.sh
  needs:
    - job: build-artifacts
      artifacts: true

# Pre-release tests
pre-release:
  stage: pre-release
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install curl zip jq -y
  script:
    - echo "Running Pre Release Checks"
    - ./.gitlab/pipeline_tests/pre-release-checks.sh
  needs:
    - job: build-artifacts
      artifacts: true
    - job: create-release

# Build the `latest` system.json and upload to gitlab generic repo
# This makes the release available in Foundry (I think?)
publish:
  stage: release
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install curl jq -y
  script:
    - echo "Releasing cyberpunk-red-core..."
    - ./.gitlab/pipeline_utils/publish.sh
  needs:
    - job: build-artifacts
      artifacts: true
    - job: pre-release
