default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - init
  - build
  - test

init:
  stage: init
  script:
    - echo "Installing dependencies..."
    - npm i
  rules:
   - when: always

build-css:
  stage: build
  script:
    - echo "Building CSS..."
    - npm run build:css
  rules:
    - when: always

lint:
  stage: test
  script:
    - echo "Linting code..."
    - npm run lint
  rules:
    - when: always

unit-test:
  stage: test
  script:
    - echo "Executing tests..."
    - npm test
  rules:
    - when: always

lang-test:
  stage: test
  script:
    - echo "Checking language file for unused strings..."
    - ./tests/test-lang-file.sh
  rules:
    - when: always

changelog-dev-test:
  stage: test
  script:
    - echo "Checking if the CHANGELOG.md changed..."
    - ./tests/test-changelog-dev-changed.sh
  allow_failure: true
