default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - init
  - build
  - test

init:
  stage: init
  script:
    - echo "Installing dependencies..."
    - npm i

build-css:
  stage: build
  script:
    - echo "Building CSS..."
    - npm run build:css

lint:
  stage: test
  script:
    - echo "Linting code..."
    - npm run lint

unit-test:
  stage: test
  script:
    - echo "Executing tests..."
    - npm test

lang-test:
  stage: test
  script:
    - echo "Checking language file for unused strings..."
    - ./.gitlab/pipeline_tests/test-lang-file.sh

changelog-dev-test:
  stage: test
  script:
    - echo "Checking if the CHANGELOG.md changed..."
    - ./.gitlab/pipeline_tests/test-changelog-dev-changed.sh
  allow_failure: true
  except:
    - master
    - dev

code-test 1/2:
  stage: test
  script:
    - echo "Checking if there are proper trace statements in all hbs files..."
    - ./.gitlab/pipeline_tests/test-hbs-trace.sh

code-test 2/2:
  stage: test
  script:
    - echo "Checking if our own localization and notification code is used..."
    - ./.gitlab/pipeline_tests/test-misc.sh
