default:
  image: node:14.15.4-alpine3.12

stages:
  - build
  - test

build-css:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm i
    - echo "Building..."
    - npm run build

unit-test:
  stage: test
  script:
    - echo "Executing tests..."
    - npm test
