default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - init
  - build
  - test

init:
  stage: init
  script:
    - echo "Installing dependencies..."
    - npm i

build-css:
  stage: build
  script:
    - echo "Building CSS..."
    - npm run build:css

lint:
  stage: test
  script:
    - echo "Linting code..."
    - npm run lint

unit-test:
  stage: test
  script:
    - echo "Executing tests..."
    - npm test

code-test 1/2:
  stage: test
  script:
    - echo "Checking if there are proper trace statements in all hbs files..."
    - ./tests/test-hbs-trace.sh
  allow_failure: true

code-test 2/2:
  stage: test
  script:
    - echo "Checking if our own localization and notification code is used..."
    - ./tests/test-misc.sh
  allow_failure: true
