base_path: .
base_url: 'https://api.crowdin.com'
pull_request_title: Localization update
pull_request_labels:
  - crowdin
  - localization
commit_message: '[ci skip]'
preserve_hierarchy: true
files:
  - source: lang/en.json
    translation: lang/%osx_locale%.json
    type: json
    translation_replace:
      _: '-'
  - source: babele/en/*.json
    translation: babele/%osx_locale%/%file_name%.json
    type: json
    translation_replace:
      _: '-'
  - source: lang/release-notes/*.en
    translation: lang/release-notes/%file_name%.%osx_locale%
    type: json
    translation_replace:
      _: '-'
