"base_path": "."
"base_url": "https://api.crowdin.com"
"pull_request_title": "Localization update"
"pull_request_labels": ["crowdin", "localization"]
"commit_message": "[ci skip]"
"preserve_hierarchy": true
files: [
    {
      "source": "/lang/_strings.json",
      "translation": "/lang/%locale%.json",
      "type": "json",
    },
    {
      "source": "/babele/_strings/*.json",
      "translation": "/babele/%locale%/%file_name%.json",
      "type": "json",
    },
  ]
