base_path: .
base_url: 'https://api.crowdin.com'
pull_request_title: Localization update
pull_request_labels:
  - crowdin
  - localization
commit_message: '[ci skip]'
preserve_hierarchy: true
files:
  - source: /src/lang/en.json
    translation: /src/lang/%locale%.json
    type: json
    translation_replace:
      _: '-'
  - source: /src/babele/en/*.json
    translation: /src/babele/%locale%/%original_file_name%
    type: json
    translation_replace:
      _: '-'
