export const CPR = {};

CPR.statList = {
    "int": "CPR.int",
    "ref": "CPR.ref",
    "dex": "CPR.dex",
    "tech": "CPR.tech",
    "cool": "CPR.cool",
    "will": "CPR.will",
    "move": "CPR.move",
    "body": "CPR.body",
    "luck": "CPR.luck",
    "emp": "CPR.emp"
}

CPR.skillCategories = {
    "awareness": "CPR.catawareness",
    "body": "CPR.catbody",
    "control": "CPR.catcontrol",
    "education": "CPR.cateducation",
    "fighting": "CPR.catfighting",
    "performance": "CPR.catperformance",
    "ranged Weapon": "CPR.catrangedweapon",
    "social": "CPR.catsocial",
    "technique": "CPR.cattech",
}

CPR.skillList = {
  "athletics": "CPR.athletics",
  "basictech": "CPR.basictech",
  "brawling": "CPR.brawling",
  "bribery": "CPR.bribery",
  "concentration": "CPR.concentration",
  "conversation": "CPR.conversation",
  "cybertech": "CPR.cybertech",
  "driving": "CPR.driving",
  "education": "CPR.education",
  "evasion": "CPR.evasion",
  "firstaid": "CPR.firstaid",
  "humanperception": "CPR.humanperception",
  "interrogation": "CPR.interrogation",
  "localexpert": "CPR.localexpert",
  "marksmanship": "CPR.marksmanship",
  "meleeweapon": "CPR.meleeweapon",
  "perception": "CPR.perception",
  "persuasion": "CPR.persuasion",
  "playinstrument": "CPR.playinstrument",
  "stealth": "CPR.stealth",
  "tracking": "CPR.tracking",
  "accounting": "CPR.accounting",
  "acting": "CPR.acting",
  "airvehicletech": "CPR.airvehicletech",
  "animalhandling": "CPR.animalhandling",
  "archery": "CPR.archery",
  "autofire": "CPR.autofire",
  "bureaucracy": "CPR.bureaucracy",
  "business": "CPR.business",
  "composition": "CPR.composition",
  "concealorrevealobject": "CPR.concealorrevealobject",
  "contortionist": "CPR.contortionist",
  "criminology": "CPR.criminology",
  "cryptography": "CPR.cryptography",
  "dance": "CPR.dance",
  "deduction": "CPR.deduction",
  "demolitions": "CPR.demolitions",
  "drivelandvehicle": "CPR.drivelandvehicle",
  "electronicsandsecuritytech": "CPR.electronicsandsecuritytech",
  "endurance": "CPR.endurance",
  "forgery": "CPR.forgery",
  "gamble": "CPR.gamble",
  "handgun": "CPR.handgun",
  "heavyweapons": "CPR.heavyweapons",
  "landvehicletech": "CPR.landvehicletech",
  "language": "CPR.language",
  "librarysearch": "CPR.librarysearch",
  "lipreading": "CPR.lipreading",
  "martialarts": "CPR.martialarts",
  "paintordraworsculpt": "CPR.paintordraworsculpt",
  "paramedic": "CPR.paramedic",
  "personalgrooming": "CPR.personalgrooming",
  "photographyandfilm": "CPR.photographyandfilm",
  "picklock": "CPR.picklock",
  "pickpocket": "CPR.pickpocket",
  "pilotairvehicle": "CPR.pilotairvehicle",
  "pilotseavehicle": "CPR.pilotseavehicle",
  "resisttortureordrugs": "CPR.resisttortureordrugs",
  "riding": "CPR.riding",
  "science": "CPR.science",
  "seavehicletech": "CPR.seavehicletech",
  "shoulderarms": "CPR.shoulderarms",
  "streetwise": "CPR.streetwise",
  "tactics": "CPR.tactics",
  "trading": "CPR.trading",
  "wardrobeandstyle": "CPR.wardrobeandstyle",
  "weaponstech": "CPR.weaponstech",
  "wildernesssurvival": "CPR.wildernesssurvival"
}

// ???? TODO -- Does this accomplish what we want for skill training cost? ????
CPR.skillDifficulties = {
    "typical": "CPR.typical",
    "difficult": "CPR.difficult",
    "role": "CPR.role"
}